baseURL = 'https://kacha.pages.dev'
languageCode = 'en-us'
title = 'Vishal Kacha | Software Developer'

[outputs]
    home = ["html"]

[[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1



[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

